### ISSUE TITLE
Content Removal Request

### ISSUE THREAD

**Issue by legalaxur** [Hestat/lw-yara#6]
Dear Sir/Madam,

Our company, AXUR, represents Magazine Luiza in issues involving the violation of intellectual property and fraud on the Internet.

Magazine Luiza is the only company authorized to use the trademark  and owns or licenses numerous trademark registrations worldwide, including, but not limited to the following registration number INPI:812376307, 812376315, 821279483, 822238195, 901356280, 901356360, 901354929, 901355046, 901355879, 901355364, 901355712, 901356476, 901356549.

The trademarks, logos, words and phrases registered by Magazine Luiza shall be exclusively used by Magazine Luiza and any other use by a third party constitutes a trademark infringement.

It has come to our attention that the reported content provides related content (see attached) to the trademark  without having obtained prior written authorization from Magazine Luiza. More specifically, this content discloses SENSITIVE DATA from our client or its customer, creating a Likelihood of Confusion between the trademark  and the reported content.

Furthermore, by misusing the trademark  on your website, you are also diluting its use, because it weakens the ability of brand identification as a single source of research and may lead consumers to believe that there is some association between Magazine Luiza and your website.

Official Website: http://www.magazineluiza.com.br/

Considering the violation of intellectual property rights of Magazine Luiza on your website, we kindly request that you remove all content available on the attached URL(s) which use the abovementioned trademark without having obtained prior authorization.

In order to avoid a lawsuit from a federal court, please, send confirmation that this email was received along with your guarantee to comply with the requests reported above.

Under penalty of perjury, we affirm that AXUR is authorized to act on behalf of the Magazine Luiza and this notification is in accordance with International Regulations of Internet and Intellectual Property Offices.

Should you require further information or should you prefer to discuss this issue, please do not hesitate to contact us through the e-mail address listed on the signature of this message.

Sincerely,

AXUR
Legal Team
legal@axur.com

ATTACHMENT:
https://github.com/Hestat/lw-yara/blob/master/includes/ninoseki-phishing-actors4.yar

**Comment by Hestat** [comment]
Hello, per the request the addresses have been removed from the indicated file.
